# Generated by Django 4.2.5 on 2023-09-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='harry', max_length=50)),
                ('address', models.CharField(default='hogwarts', max_length=100)),
                ('phno', models.CharField(default='', max_length=50)),
                ('field', models.CharField(default='flying', max_length=50)),
                ('email', models.EmailField(default='abc@gmail.com', max_length=255)),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='harry', max_length=50)),
                ('address', models.CharField(default='hogwarts', max_length=100)),
                ('phno', models.CharField(default='', max_length=50)),
                ('field', models.CharField(default='flying', max_length=50)),
                ('email', models.EmailField(default='abc@gmail.com', max_length=255)),
            ],
        ),
    ]
