# Generated by Django 4.2.5 on 2023-09-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='field',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phno',
            field=models.CharField(default='987654321', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phno',
            field=models.CharField(default='987654321', max_length=50),
        ),
    ]
